# This workflow will copy the static content to the gh-pages branch and run the Python script to generate further content from the data files

name: Python application

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Copy static content
      run: |
        git config user.name 'HUSZERL G.'
        git config user.email 'huszerl@mit.bme.hu'
        echo "--- Configured"
        pwd
        mkdir ../generated
        git worktree add -b gh-pages ../generated
        echo "--- Worktree created"
        cp static/* ../generated/
        ls
        echo "--- Starting generation"
        mkdir gen/
        cd scripts
        python street_generator.py
        cd ..
        echo "--- Generation finished"
        cp -r gen/ ../generated/
        cd ../generated/
        git add ./*
        git commit -m "Updating pages on ${{ steps.date.outputs.date }}"
        echo "--- Committed"
        git push --force --set-upstream origin gh-pages
        echo "--- Pushed"
        ls ../utest
        echo "--- Root directory listed"
        cd ../utest
        git worktree remove ../generated
