# This workflow will copy the static content to the gh-pages branch and run the Python script to generate further content from the data files

name: Python application

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Copy static content
      run: |
        git config user.name 'HUSZERL Gábor'
        git config user.email 'huszerl@mit.bme.hu'
        git worktree add ../generated gh-pages
        cp static/* ../generated/
        cd ../generated/
        git branch gh-pages
        git add ./*
        git commit -m "Updating pages on %d"
        git push origin
        cd ../main
        git worktree remove
